Repository Rupandangol/vue-food-api, pull requests merged in 2020-12, with the labels that each got.

#2 GOG-29 design implementation
  home/card.vue
  home/index.vue
  home/list.vue
Labels: documentation

#3 GOG-30 Setting flatlist via component
  home/list.vue
  home/listBlock.vue
Labels: enhancement

#4 GOG-32 api integration and utiliztion 1st part
  home/card.vue
  home/index.vue
  home/list.vue
  home/listBlock.vue
Labels: documentation

#5 GOG-33 remove header/ add native base as header
  App.vue
  home/index.vue
  package-lock.json
  package.json
Labels: bug
